@startuml

boundary Mandarin

boundary Application
entity ResultProcessor
control ResponseHandler
boundary MandarinApiGem
control Responder

Mandarin -> Application : HttpRequest
Application -> MandarinApiGem : RequestParams
MandarinApiGem -> Responder : RequestParams
Responder -> ResponseHandler :  "<font color=green><b>SuccessResponse"
Responder -> ResponseHandler :  "<font color=red><b>FailureResponse"
ResponseHandler -> ResultProcessor : Result

@enduml
